import Card from "@/components/Card";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Birlikte Güçlüyüz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p className="text-6xl text-center text-pink-600 mt-10 font-bold">
            Kim yapar?
          </p>
          <p className="text-6xl text-center text-pink-600 mt-4 font-bold">
            BEN YAPARIM
          </p>
          <p className="text-center max-w-xl w-1/2 m-auto my-20">
            Ben Yaparım! <br /> Afet zamanlarında belli yetkinliklere sahip acil
            gönüllü ihtiyacı duyan kurumlarla, bu ihtiyacı karşılayabilecek
            gönüllü uzmanları bir araya getiren platformdur.
          </p>
          <p className="text-xl text-center text-pink-600 mt-10 font-bold">
            Aktif çağrıları incele
          </p>
        </div>
        <Card />
      </main>
    </>
  );
}
